baseURL = 'https://ismacortes.github.io/Hugo/'
languageCode = 'en-us'
title = 'Página real'
theme = 'hugo-PaperMod-master'

[menu]
  [[menu.main]]
	identifier = "contacto"
	name = "Contacto"
	title = "Contacto"
	url = "/contacto/"
	weight = 0
  [[menu.main]]
	identifier = "posts"
	name = "Posts"
	title = "Posts"
	url = "/posts/"
	weight = 0